### ISSUE TITLE
revert code example to teach += and -=

### ISSUE THREAD

**Issue by theophani** [OpenTechSchool/js-beginners-2#23]
The example code was updated to show <code>+=</code> and <code>-=</code> before the operators were taught. It should be reverted in both English and German.

![https://img.skitch.com/20120722-x6bda11d431aqbnk1p2h8rfx2d.jpg](https://img.skitch.com/20120722-x6bda11d431aqbnk1p2h8rfx2d.jpg)

**Comment by molily** [comment]
Sorry, I thought that was an error because of the explanation below. I had a chat with Johannes an our idea was to use the operators because they were mentioned below, otherwise they don’t need to be mentioned at all.

I totally agree to remove them because today I had to explain several time what <code>+=</code>/<code>-=</code> means even with the explanation below.

**Comment by theophani** [comment]
Ah, I see how that happened. Yeah, maybe the whole bit about the operators could be cut entirely, or given as "Bonus material". (Fronx mentioned and I agree that there were other parts that would be better as "Bonus material" that is provided for exploring ideas, that aren't entirely required for the exercise.)
